sudo: required
services:
  - docker

before_install: 
  - docker build -t crisleicon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true crisleicon/docker-react npm run test

language: generic

deploy: 
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-sa-east-1-480329405117"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY